### ISSUE TITLE
Build portion of script is failing. Was working two days earlier.

### ISSUE THREAD

**Issue by Bas-Man** [victoriadrake/hugo-remote#10]
**Describe the bug**
Getting a failure on the build part of the script.

**From logs.**

npm notice created a lockfile as package-lock.json. You should commit this file.
36
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
37
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
38
npm WARN autoprefixer@10.0.2 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
39
npm WARN postcss-cli@8.2.0 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
40
npm WARN postcss-reporter@7.0.1 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
41
npm WARN workspace@1.0.0 No description
42

43
+ autoprefixer@10.0.2
44
+ postcss-cli@8.2.0
45
added 103 packages from 71 contributors and audited 104 packages in 5.353s

This worked just two days ago.

Any thoughts?

**Comment by victoriadrake** [comment]
Looks like you probably got there already, but this is caused by the [breaking change in `postcss-cli@8.0.0`](https://github.com/postcss/postcss-cli/releases/tag/8.0.0)

Just need to install `postcss`!

**Comment by Bas-Man** [comment]
Actually. It was caused by user error.

I was pushing an update to master. Where the site content showed no actual
update to the Hugo site.
