### ISSUE TITLE
trying to migrate from Jekyll to Hugo Git error.

### ISSUE THREAD

**Issue by Bas-Man** [victoriadrake/hugo-remote#2]
Hi,

I am attempting to move my site from jekyll to hugo. I am trying to use your workflow. I am almost there. But I am getting an error  "Deploy with hugo-remote"

Everything seem ok until the end.

from logs:
create mode 100644 tags/plex/index.xml
create mode 100644 tags/thoughts/index.html
create mode 100644 tags/thoughts/index.xml
error: unknown option `---END'
usage: git push [<options>] [<repository> [<refspec>...]]

I still have my originally content from jekyll. I am wondering if I need to clear out my old Jekyll content?

Any suggestions?

**Comment by victoriadrake** [comment]
Hi there! Without taking a look at your codebase I'm afraid I don't have a helpful suggestion other than the one you've already proposed. It seems the string "---END" is somehow being passed to the `git push` command. Perhaps this string is part of a Jekyll-related file that you can remove?

Did you set your [environment variables](https://github.com/victoriadrake/hugo-remote#2-set-your-environment-variables-and-add-this-action-in-a-workflow)?

**Comment by Bas-Man** [comment]
I have cleared the original site content. There was no improvement. I will work through the guide again and see if I missed anything.

**Comment by Bas-Man** [comment]
I am happy to make my source repo public for a bit.

Things to note:
I created  an ssh key pair and added master to the the source repo
add the pub key to the destination repo as a deploy key.
my local git is on a mac running git version 2.20.1 (Apple Git-117)
I am still getting the same error.
No indication of permissions, but I am not familiar with using Token at present.
I am wondering if the ---END is coming from the master key stored in the source repo as a secret

**Comment by Bas-Man** [comment]
Hi,

I think I set up my variables based on what I saw in the sample yml file. 
I have been publishing manually. And found that I had forgotten to set HUGO_ENV before generating my site. But I think that's a separate issue.

I have a couple of questions.
Do I need to set up a git submodule linking public to the username.github.io repo? I have seen this in other guides, but I am not sure if they are related to the workflow you have created.

Am I setting up my secrets correctly.
1) generate ssh keys.
2) copy private key to secrets of the hidden source repo.
3) copy the pub key to the username.github.io deploy secret
 
Or am I going about this in the wrong manner?

**Comment by victoriadrake** [comment]
Oh, I think I may see the problem. The secret expected by the action is not an SSH key, but a [Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token#creating-a-token). Please examine step 1 in the README for further instruction. Let me know if that helps!

**Comment by Bas-Man** [comment]
I have created a new personal secret.

New error message:

fatal: could not read Password for 'https://github.com': No such device or address

**Comment by Bas-Man** [comment]
I added the personal secret to the destination repo.

So its not clear to me where I should use the personal secret token after it's been created.

**Comment by Bas-Man** [comment]
Ok. I have added the generated token to both the source and destination repos. and the Build works.

But I will have to add another issue. (HUGO_ENV) missing.
