### ISSUE TITLE
Site Builds without setting HUGO_ENV=production / missing Google Analytics

### ISSUE THREAD

**Issue by Bas-Man** [victoriadrake/hugo-remote#3]
Hi

I got the build to work, but unfortunately the build environment does not have HUG0_ENV set to production.

This means that some partials and internal partials are not being added to the dployment.

Could you please add the environment variable so that this extra partials are added. 
I am using the https://github.com/theNewDynamic/gohugo-theme-ananke.githttps://github.com/theNewDynamic/gohugo-theme-ananke.git theme.

**Comment by victoriadrake** [comment]
This seems to be a theme-specific requirement, or at least the method for passing in the variable differs from the Hugo documentation on the use of the [`-e` flag on the `hugo` command](https://gohugo.io/commands/hugo/). I'd be up for implementing an ENV line for additional build commands, but not for a change that's quite this specific.

Currently, you can modify the action to suit specific needs by using the [workflow YAML file directly](https://github.com/victoriadrake/hugo-remote#use-the-workflow-yaml-file-directly).

Would you like to take a crack at updating your PR to add an environment variable line that can pass arbitrary additional flags to `hugo`?

**Comment by Bas-Man** [comment]
Hi,

You are correct. There is an -e flag. and that might be a better option.
Your suggestion would also allow for passing --minify and such as well.

I am not familiar with workflows. But I could take a look around and see how it might be done. Might take a little time :)

**Comment by Bas-Man** [comment]
My HUGO_ENV issue is a theme related  issue. I have changed its code to use 
```txt
hugo.IsProduction
```

However I  will still look into adding arguments for --minify which I think just needs to be a flag perhaps.
